# Generated by Django 5.2.8 on 2025-12-07 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Peso Total do Produto (kg)')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Largura (cm)')),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Altura (cm)')),
                ('depth', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Profundidade (cm)')),
                ('filament_consumption', models.DecimalField(decimal_places=2, default=0, help_text='Consumo de filamento em peso (gramas) necessário para a produção.', max_digits=10, verbose_name='Consumo de Filamento (gramas)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ('name',),
            },
        ),
    ]
