# Generated by Django 5.2.8 on 2025-12-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='access_credentials',
            field=models.TextField(blank=True, null=True, verbose_name='Acessos/Senhas (Notas)'),
        ),
        migrations.AddField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail Oficial'),
        ),
        migrations.AddField(
            model_name='company',
            name='pix_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='company',
            name='state_registration',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Inscrição Estadual (IE)'),
        ),
    ]
