# Generated by Django 5.2.8 on 2025-12-07 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_access_credentials_company_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='document',
        ),
    ]
